<a href="https://colab.research.google.com/github/goliharini19/rl26/blob/main/1544_RLASMNT4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
M=input("enter number of machines")
M=int(M)
machines=[]
for i in range(M):
    name=input("enter machine name")
    machines.append(name)
print(machines)

enter number of machines3
enter machine namea
enter machine nameb
enter machine namec
['a', 'b', 'c']


In [ ]:
import numpy as np

N_play=5
N=np.zeros((M,N_play))
R=np.zeros((M,N_play))
Q=np.zeros((M,N_play))
UCB=[0,0,0]
Q_old=0

for machine in machines:
    print(f"Play with machine {machine}")
    r=input("enter reward")
    r=int(r)
    id=machines.index(machine)

    N[id,0]=1
    R[id,0]=r
    Q[id,0]=Q[id,0]+(R[id,0]-Q[id,0])/N[id,0]

print(N)
print(R)
print(Q)

Play with machine a
enter reward8
Play with machine b
enter reward5
Play with machine c
enter reward2
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[8. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]]
[[8. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]]


In [ ]:
import math as mt
import numpy as np

play=1
c=2
t=3

UCB = np.zeros(M)

while(play<N_play):
    t=t+play

    for id in range(M):
        UCB[id]=Q[id,play-1]+c*mt.sqrt(mt.log(t)/np.sum(N[id,:]))

    id_max=np.argmax(UCB)

    print(f"play with machine {machines[id_max]}")
    # Fix: Validate input to ensure it's an integer
    while True:
        r_str = input("enter reward")
        if r_str.strip().isdigit() or (r_str.strip().startswith('-') and r_str.strip()[1:].isdigit()):
            r = int(r_str)
            break
        else:
            print("Invalid input. Please enter an integer for the reward.")

    N[id_max,play]=1
    R[id_max,play]=r

    Q[id_max,play]=Q[id_max,play-1]+(R[id_max,play]-Q[id_max,play-1])/np.sum(N[id_max,:])

    play=play+1

print(N)
print(R)
print(Q)

play with machine a
enter reward8
play with machine a
enter reward5
play with machine a
enter reward2
play with machine a
enter reward01
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[8. 8. 5. 2. 1.]
 [5. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]]
[[8.    8.    7.4   6.32  5.256]
 [5.    0.    0.    0.    0.   ]
 [2.    0.    0.    0.    0.   ]]


In [ ]:
import math as mt

play=1
c=2
t=3

while(play<N_play):
    t=t+play
    Q[:,play-1]=Q[:,play-1]

    for id in range(M):
        UCB[id]=Q[id,play-1]+c*mt.sqrt(mt.log(t)/np.sum(N[id,:]))
    print(UCB)

    id_max=np.argmax(UCB)
    print(f"play with machine {machines[id_max]}")

    r=input("enter reward")
    r=int(r)

    N[id_max,play]=1
    R[id_max,play]=r

    Q[id_max,play]=Q[id_max,play-1]+(r-Q[id_max,play-1])/np.sum(N[id_max,:])

    play=play+1

print(N)
print(R)
print(Q)

[9.05310754 7.35482005 4.35482005]
play with machine a
enter reward2
[7.99725001 2.6771324  2.6771324 ]
play with machine a
enter reward8
[8.36581283 2.96460761 2.96460761]
play with machine a
enter reward1
[7.26446623 3.20309185 3.20309185]
play with machine a
enter reward5
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[8. 2. 8. 1. 5.]
 [5. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]]
[[8.     6.8    7.04   5.832  5.6656]
 [5.     0.     0.     0.     0.    ]
 [2.     0.     0.     0.     0.    ]]
